## Useful constants. Generated by generate_sdk_list.py

DEFAULT_VERSION = "2.3.1"

SDK_VERSION_SHA256 = {
    "3.5.0": {
        "linux_amd64": "271e59de861684156515b8aa53eafa0cd242017595652c52a072b1812bbd3775",
        "darwin_amd64": "b75c1f1532fc27187097f9ccb6c4d8e8ea751e7e9a238a1c1f2c58b171eadad7"
    },
    "3.4.1": {
        "linux_amd64": "4b9c6b3afec09bd1c1f1a67ed11c275854b9cbddc1654ebdb77c3b0b95f4e065",
        "darwin_amd64": "6c4600ff2a4ed02c073f0c9d305bf89948e02b3767d2d5a810d0138d269c133d"
    },
    "3.4.0": {
        "linux_amd64": "cf90dad16d27a9c31db11f2c326aad926036610a75be03f342e28136ae64cf47",
        "darwin_amd64": "4d77ba9e9fc214dbd16077fa069bf40606bfe57c359b3e24fbf38919922d7b5f"
    },
    "3.3.0": {
        "linux_amd64": "f9fb1a8e329dfe3be635ccdec3c7d3a6df4092ba13243bfcb89111b12343eb4f",
        "darwin_amd64": "d5c3ed529d8156005ce15de43f6f505abc4beb63e9b0ac9e215edaecb64c2ce3"
    },
    "3.2.0": {
        "linux_amd64": "102bb0f586dcb50951aded67856483a2ee114057c56475b3cda6051a12832a72",
        "darwin_amd64": "871a0f21af99d895ef534fb11704eb0e4a1f8b55df58906f625702faa65f64e6"
    },
    "3.1.0": {
        "linux_amd64": "a4af6a2110cf506855cdc86d0291c6e76203ae9fb3c918f7fdc05e7962e4b488",
        "darwin_amd64": "2a6c5e0e276b65cfbe173fca07b318ecff1752bf947002641b808c4a40187f2c"
    },
    "3.0.0": {
        "linux_amd64": "d762c5cd954f9eb8620c64d27fc413e383e8100108d9edaee2211457165d2dff",
        "darwin_amd64": "c8bcbb32de6a6e17676a21ce202d2da7d97f342582f42d4dfe672260b7f2c100"
    },
    "3.0.0-rc.0": {
        "linux_amd64": "5dc229842edc6e35d51c6f8ee3c8dbfcd7989665ebaa0d27a79bdd6e6fe80e39",
        "darwin_amd64": "af0c319343b58a340eb16c3c3d389027dd6dd741e733d4809c6ed4d6fa4a60d3"
    },
    "3.0.0-beta.1": {
        "linux_amd64": "ae80ae35b75fda988ad23cb48ae658d653d802484b21d9c55dd54ddeadfa65b3",
        "darwin_amd64": "3dc49db6550b3256132db2554e34ec029ce70042c61dd2f534acadee3365b8a7"
    },
    "3.0.0-beta.0": {
        "linux_amd64": "8178d61b1e8214f8d0871719614143f42f032655b77a64ea4e5c364fec2c8acd",
        "darwin_amd64": "991cbd04b162f31f40f5eb430286f23ac38b16bd57f0c85fcc85b2a00adef8f9"
    },
    "2.3.2": {
        "linux_amd64": "c65b86f497726fcb8b887d55c10a68e38a503aa736c0d02b2cce11df267ad91d",
        "darwin_amd64": "7e7dc6f5b106909a13a24beea73427940a6ed81a8dea66d65b185dc2c71dcc28"
    },
    "3.0.0-alpha.1": {
        "linux_amd64": "dab17609a0b7a8d89244cd2c739c52bb777067c61b867d50a9def869c98cd560",
        "darwin_amd64": "bf4baab7587747f084d9b6e308a5e07fb56cdc032b907c81bfb230558a301052"
    },
    "3.0.0-alpha.0": {
        "linux_amd64": "099faba3dda57585bbfaa9b090fa3bc724c124858f5d5c78dc8a507297456d0d",
        "darwin_amd64": "76abdc522426bf70cdd5118400563aa1bb62638eaa0e4c8486d30f4178403867"
    },
    "2.3.1": {
        "linux_amd64": "ff496970f209706763f2aba2bdcefc2de8d00085b3b972b5790117b59ea4ed10",
        "darwin_amd64": "39314d45053b6c31eb17e35c9b8d923f8a38277a9a136448345dd4b7f0f308f4"
    },
    "2.3.0": {
        "linux_amd64": "a8ffea619f8d6e6c9fab2df8543cf0912420568e3979f44340a7613de5944141",
        "darwin_amd64": "b44f6c7ba1edf0046354ff29abffee3410d156fabae6eb3fa62da806988aa8bd"
    },
    "2.2.0": {
        "linux_amd64": "9ef35a4a4e92408f7606f1dd1e68fe986fa222a88d34e40ecc07b6ffffcc8c12",
        "darwin_amd64": "5ccb9803d391e819b606b0c702610093619ad08e429ae34401b3e4d448dd2553"
    },
    "2.1.0": {
        "linux_amd64": "79820786964eaecba1e90c413d8399600fde7917dfd1b0b74d6536b33f020077",
        "darwin_amd64": "3ab68c805a7dea461023e2c52b906c0ecac6ecb1b9a597e4a98611bce9c1fe56"
    },
    "2.0.1": {
        "linux_amd64": "e8d287535c79013bfebcee22f748153686128926ae5992f023725e7b17996a04",
        "darwin_amd64": "a2cd518da553584aee2e8a74818da1521f5dd4a9a4a97c8e18b2634e8a8266ca"
    },
    "2.0.0": {
        "linux_amd64": "858d84aa3e8bb6528d7dd4dbab4e8fceb59c8ea7905918bc72dc719d784c40f3",
        "darwin_amd64": "4679b5d57c857a0d3c763e9eefb4c797804a184fcae7827a3ca9abc990accc70"
    },
    "2.0.0-rc.0": {
        "linux_amd64": "d4e5f8adf005e59ad1b2b8bf88f9e6841d500a473fb6f7dde7b17ca94b12e1df",
        "darwin_amd64": "970c74143287731c60bb171a1c90f2fb18c99b5e989af38db0d5094b96ded02a"
    },
    "2.0.0-beta.0": {
        "linux_amd64": "52a81e9277b24ad3693551be142cad05efc0e4d5a35a1f99749e847d6b5f952a",
        "darwin_amd64": "8ade93ba2821ff8e87a9266e91409a1a8ef7a8c6afe7143e68c356b675df17f4"
    },
    "2.0.0-alpha.4": {
        "linux_amd64": "623849d15580544790805326532d1d3e0e6bb92da770e908048049dda724be4d",
        "darwin_amd64": "e0937eb925cf0e68efa26b15e0c57feb4b7dbb0176f1acd69a68a78c5c925081"
    },
    "2.0.0-alpha.3": {
        "linux_amd64": "ff6c1eb39eac6fac5c63a773f4690643603955e8672991d8da12fce0b3708d28",
        "darwin_amd64": "eb401e5aab74a8344e9cb58cb9263ed0dce74b218e6de9fd71d0009ee08ac93c"
    },
    "2.0.0-alpha.2": {
        "linux_amd64": "d9d3f471cb54f4e802ed763d0706720be45f65c7bd36e45ab28db7840028bf72",
        "darwin_amd64": "795e49c0c9111f27307f63af9271f736efc1d2c8d2379be0087ff26321a7719c"
    },
    "2.0.0-alpha.1": {
        "linux_amd64": "8647fcac60166ae211b9e198596452003c5887dd5b0d8b79427aa4fe3357f125",
        "darwin_amd64": "c19887e34f5ff008d89ae3e86aeecd0560002c0dacd36f870b46741e9426b551"
    },
    "2.0.0-alpha.0": {
        "linux_amd64": "edee6582e8cf0c2836d509ed3939b7c3a1006c28bb57f22f2a3d4a5f4699ae99",
        "darwin_amd64": "9405023af5ddbadf5196cf450c412e3d328c995a86f097f69222c26110c003b2"
    },
    "1.0.8": {
        "linux_amd64": "7dfaf7a38d69c77f046e85aeabfe96f7cdd88634feab3ecc0bb03f9da7e69ad3",
        "darwin_amd64": "a2a2db0db67c61e7ae958b9ff393e44a7032cd11b5e46acf9bd0a547e3fb9915"
    },
    "1.0.7": {
        "linux_amd64": "9f7f55708429122b2111a5012977265522228764e756e0094f0128605f85b462",
        "darwin_amd64": "f58b9b33a3a61be2313c1747c91c46436deede87d20ad13287618d5e54e9d315"
    },
    "1.0.6": {
        "linux_amd64": "a622eebdcc95984d3a3d87d0acd2d7c02b463f4db23b1b22020a2bc77c032668",
        "darwin_amd64": "0a056b58af62e4204cc65e0a7a39236396acff1935fe10effd52bf226ea6dbc3"
    },
    "1.0.5": {
        "linux_amd64": "e729c74f6a1b3ab9c416642f372b84df60d07c84f64302f1f7e3fe7a9f9411e5",
        "darwin_amd64": "a510ef34d947764f57385e11990ba70560bf2d520f56849160174d2c18544063"
    }
}